language: go

before_install:
  - source ./goenv
  - go get -u golang.org/x/tools/cmd/stringer
  - go get github.com/stretchr/testify
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/vendor/bin"

install:
  - make

script:
  - make test
