language: go

before_install:
  - source goenv
  - source goinstall
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/vendor/bin"

script:
  - go generate c6/ast c6
  - go build c6
  - go test -coverprofile=profile.cov c6
  - vendor/bin/goveralls -coverprofile=profile.cov -service=travis-ci
