language: go

before_install:
  - source goenv
  - source goinstall
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/vendor/bin"

script:
  - make
  - make test
  - make cov

after_success:
  - vendor/bin/goveralls -coverprofile=c6.cov -service=travis-ci
