language: go

before_install:
  - source goenv
  - source goinstall
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/vendor/bin"

script:
  - go generate c6 c6/ast
  - go build c6 c6/ast
  - go test -coverprofile=c6.cov c6
  - go test -coverprofile=c6-ast.cov c6/ast

after_success:
  - vendor/bin/goveralls -coverprofile=profile.cov -service=travis-ci
